convert background.gif -type Grayscale ../background.gif
convert cellpic1.gif -type Grayscale ../cellpic1.gif
convert cellpic2.jpg -type Grayscale ../cellpic2.jpg
convert cellpic2_rtl.jpg -type Grayscale ../cellpic2_rtl.jpg
convert cellpic3.gif -type Grayscale ../cellpic3.gif
convert cellpic.gif -type Grayscale ../cellpic.gif
convert created_by.jpg -type Grayscale ../created_by.jpg
convert icon_mini_faq.gif -type Grayscale ../icon_mini_faq.gif
convert icon_mini_groups.gif -type Grayscale ../icon_mini_groups.gif
convert icon_mini_login.gif -type Grayscale ../icon_mini_login.gif
convert icon_mini_members.gif -type Grayscale ../icon_mini_members.gif
convert icon_mini_message.gif -type Grayscale ../icon_mini_message.gif
convert icon_mini_profile.gif -type Grayscale ../icon_mini_profile.gif
convert icon_mini_register.gif -type Grayscale ../icon_mini_register.gif
convert icon_mini_search.gif -type Grayscale ../icon_mini_search.gif
convert no_avatar.gif -type Grayscale ../no_avatar.gif
convert spacer.gif -type Grayscale ../spacer.gif
convert whosonline.gif -type Grayscale ../whosonline.gif
