convert ball.gif -type grayscale ../ball.gif
convert button_pm_new.gif -type grayscale ../button_pm_new.gif
convert button_pm_reply.gif -type grayscale ../button_pm_reply.gif
convert button_topic_locked.gif -type grayscale ../button_topic_locked.gif
convert button_topic_new.gif -type grayscale ../button_topic_new.gif
convert button_topic_reply.gif -type grayscale ../button_topic_reply.gif
convert calendar.gif -type grayscale ../calendar.gif
convert chat.gif -type grayscale ../chat.gif
convert forums.gif -type grayscale ../forums.gif
convert gallery.gif -type grayscale ../gallery.gif
convert help.gif -type grayscale ../help.gif
convert home.gif -type grayscale ../home.gif
convert icon_contact_aim.gif -type grayscale ../icon_contact_aim.gif
convert icon_contact_email.gif -type grayscale ../icon_contact_email.gif
convert icon_contact_icq.gif -type grayscale ../icon_contact_icq.gif
convert icon_contact_jabber.gif -type grayscale ../icon_contact_jabber.gif
convert icon_contact_msnm.gif -type grayscale ../icon_contact_msnm.gif
convert icon_contact_pm.gif -type grayscale ../icon_contact_pm.gif
convert icon_contact_www.gif -type grayscale ../icon_contact_www.gif
convert icon_contact_yahoo.gif -type grayscale ../icon_contact_yahoo.gif
convert icon_post_delete.gif -type grayscale ../icon_post_delete.gif
convert icon_post_edit.gif -type grayscale ../icon_post_edit.gif
convert icon_post_info.gif -type grayscale ../icon_post_info.gif
convert icon_post_quote.gif -type grayscale ../icon_post_quote.gif
convert icon_post_report.gif -type grayscale ../icon_post_report.gif
convert icon_user_offline.gif -type grayscale ../icon_user_offline.gif
convert icon_user_online.gif -type grayscale ../icon_user_online.gif
convert icon_user_profile.gif -type grayscale ../icon_user_profile.gif
convert icon_user_search.gif -type grayscale ../icon_user_search.gif
convert icon_user_warn.gif -type grayscale ../icon_user_warn.gif
