convert announce_read.gif -type Grayscale ../announce_read.gif
convert announce_read_locked.gif -type Grayscale ../announce_read_locked.gif
convert announce_read_locked_mine.gif -type Grayscale ../announce_read_locked_mine.gif
convert announce_read_mine.gif -type Grayscale ../announce_read_mine.gif
convert announce_unread.gif -type Grayscale ../announce_unread.gif
convert announce_unread_locked.gif -type Grayscale ../announce_unread_locked.gif
convert announce_unread_locked_mine.gif -type Grayscale ../announce_unread_locked_mine.gif
convert announce_unread_mine.gif -type Grayscale ../announce_unread_mine.gif
convert convert.sh -type Grayscale ../convert.sh
convert forum_link.gif -type Grayscale ../forum_link.gif
convert forum_read.gif -type Grayscale ../forum_read.gif
convert forum_read_locked.gif -type Grayscale ../forum_read_locked.gif
convert forum_read_subforum.gif -type Grayscale ../forum_read_subforum.gif
convert forum_unread.gif -type Grayscale ../forum_unread.gif
convert forum_unread_locked.gif -type Grayscale ../forum_unread_locked.gif
convert forum_unread_subforum.gif -type Grayscale ../forum_unread_subforum.gif
convert icon_post_target.gif -type Grayscale ../icon_post_target.gif
convert icon_post_target_unread.gif -type Grayscale ../icon_post_target_unread.gif
convert icon_topic_attach.gif -type Grayscale ../icon_topic_attach.gif
convert icon_topic_latest.gif -type Grayscale ../icon_topic_latest.gif
convert icon_topic_newest.gif -type Grayscale ../icon_topic_newest.gif
convert icon_topic_reported.gif -type Grayscale ../icon_topic_reported.gif
convert icon_topic_unapproved.gif -type Grayscale ../icon_topic_unapproved.gif
convert imageset.cfg -type Grayscale ../imageset.cfg
convert poll_center.gif -type Grayscale ../poll_center.gif
convert poll_left.gif -type Grayscale ../poll_left.gif
convert poll_right.gif -type Grayscale ../poll_right.gif
convert site_logo.gif -type Grayscale ../site_logo.gif
convert sticky_read.gif -type Grayscale ../sticky_read.gif
convert sticky_read_locked.gif -type Grayscale ../sticky_read_locked.gif
convert sticky_read_locked_mine.gif -type Grayscale ../sticky_read_locked_mine.gif
convert sticky_read_mine.gif -type Grayscale ../sticky_read_mine.gif
convert sticky_unread.gif -type Grayscale ../sticky_unread.gif
convert sticky_unread_locked.gif -type Grayscale ../sticky_unread_locked.gif
convert sticky_unread_locked_mine.gif -type Grayscale ../sticky_unread_locked_mine.gif
convert sticky_unread_mine.gif -type Grayscale ../sticky_unread_mine.gif
convert topic_moved.gif -type Grayscale ../topic_moved.gif
convert topic_read.gif -type Grayscale ../topic_read.gif
convert topic_read_hot.gif -type Grayscale ../topic_read_hot.gif
convert topic_read_hot_mine.gif -type Grayscale ../topic_read_hot_mine.gif
convert topic_read_locked.gif -type Grayscale ../topic_read_locked.gif
convert topic_read_locked_mine.gif -type Grayscale ../topic_read_locked_mine.gif
convert topic_read_mine.gif -type Grayscale ../topic_read_mine.gif
convert topic_unread.gif -type Grayscale ../topic_unread.gif
convert topic_unread_hot.gif -type Grayscale ../topic_unread_hot.gif
convert topic_unread_hot_mine.gif -type Grayscale ../topic_unread_hot_mine.gif
convert topic_unread_locked.gif -type Grayscale ../topic_unread_locked.gif
convert topic_unread_locked_mine.gif -type Grayscale ../topic_unread_locked_mine.gif
convert topic_unread_mine.gif -type Grayscale ../topic_unread_mine.gif
convert topic_unread.psd -type Grayscale ../topic_unread.psd
convert upload_bar.gif -type Grayscale ../upload_bar.gif
